// SPDX-License-Identifier: MIT

package service_test

import (
	"bytes"
	"encoding/hex"
	"testing"

	"github.com/otfabric/go-bacnet"
	"github.com/otfabric/go-bacnet/service"
)

func TestEncodeCreateObjectWithIdentifierAndIndex(t *testing.T) {
	id := bacnet.ObjectIdentifier{Type: bacnet.ObjectTypeAnalogValue, Instance: 55}
	idx := uint32(0)
	raw, err := service.EncodeCreateObject(service.CreateObjectRequest{
		ObjectIdentifier: &id,
		InitialValues: []service.PropertyValue{{
			Property: bacnet.PropertyReference{Identifier: bacnet.PropertyObjectName, ArrayIndex: &idx},
			Value:    bacnet.ApplicationValue{Kind: bacnet.ValueCharacterString, Character: bacnet.CharacterString{Value: "x"}},
		}},
	})
	if err != nil || len(raw) < 8 {
		t.Fatalf("%v len=%d", err, len(raw))
	}
}

func TestDecodeCreateObjectACKForms(t *testing.T) {
	raw, err := bacnet.AppendContextObjectID(nil, 0, bacnet.ObjectIdentifier{Type: bacnet.ObjectTypeAnalogValue, Instance: 3})
	if err != nil {
		t.Fatal(err)
	}
	got, err := service.DecodeCreateObjectACK(raw, bacnet.DefaultDecodeLimits())
	if err != nil {
		raw2, err2 := bacnet.AppendApplicationValue(nil, bacnet.ObjectIDValue(bacnet.ObjectIdentifier{Type: bacnet.ObjectTypeAnalogValue, Instance: 3}))
		if err2 != nil {
			t.Fatal(err2)
		}
		got, err = service.DecodeCreateObjectACK(raw2, bacnet.DefaultDecodeLimits())
		if err != nil {
			t.Fatal(err)
		}
	}
	if got.Object.Instance != 3 {
		t.Fatalf("%+v", got)
	}
}

func TestCreateObjectWireMatchesBACnet4J(t *testing.T) {
	// Independently generated by BACnet4J 6.1.0 CreateObjectRequest.write.
	const byID = "0e1c008000650f1e094d2e750f0041562d435245415445442d3130312f1f"
	const byType = "0e09020f1e094d2e750f0041562d435245415445442d3130312f1f"
	wantID, err := hex.DecodeString(byID)
	if err != nil {
		t.Fatal(err)
	}
	wantType, err := hex.DecodeString(byType)
	if err != nil {
		t.Fatal(err)
	}

	id := bacnet.ObjectIdentifier{Type: bacnet.ObjectTypeAnalogValue, Instance: 101}
	ot := bacnet.ObjectTypeAnalogValue
	iv := []service.PropertyValue{{
		Property: bacnet.PropertyReference{Identifier: bacnet.PropertyObjectName},
		Value: bacnet.ApplicationValue{
			Kind:      bacnet.ValueCharacterString,
			Character: bacnet.CharacterString{Value: "AV-CREATED-101"},
		},
	}}

	gotID, err := service.EncodeCreateObject(service.CreateObjectRequest{
		ObjectIdentifier: &id,
		InitialValues:    iv,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(gotID, wantID) {
		t.Fatalf("by-id\n got %x\nwant %x", gotID, wantID)
	}
	gotType, err := service.EncodeCreateObject(service.CreateObjectRequest{
		ObjectType:    &ot,
		InitialValues: iv,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(gotType, wantType) {
		t.Fatalf("by-type\n got %x\nwant %x", gotType, wantType)
	}

	dec, err := service.DecodeCreateObject(gotID, bacnet.DefaultDecodeLimits())
	if err != nil || dec.ObjectIdentifier == nil || dec.ObjectIdentifier.Instance != 101 {
		t.Fatalf("%+v %v", dec, err)
	}
	if len(dec.InitialValues) != 1 || dec.InitialValues[0].Value.Character.Value != "AV-CREATED-101" {
		t.Fatalf("initial values: %+v", dec.InitialValues)
	}

	// Pre-v0.2.3 bare CHOICE + [2] list must fail.
	oldBare := []byte{0x1c, 0x00, 0x80, 0x00, 0x65}
	if _, err := service.DecodeCreateObject(oldBare, bacnet.DefaultDecodeLimits()); err == nil {
		t.Fatal("expected reject of bare objectSpecifier")
	}
	oldList2 := append(append([]byte{}, oldBare...), 0x2e, 0x09, 0x4d, 0x2e, 0x75, 0x01, 0x00, 0x78, 0x2f, 0x2f)
	if _, err := service.DecodeCreateObject(oldList2, bacnet.DefaultDecodeLimits()); err == nil {
		t.Fatal("expected reject of listOfInitialValues [2]")
	}

	// Duplicate objectSpecifier / empty CHOICE / wrong inner tag.
	dup := append(append([]byte{}, wantID[:7]...), wantID[:7]...) // two [0] wrappers (0e..0f)
	if _, err := service.DecodeCreateObject(dup, bacnet.DefaultDecodeLimits()); err == nil {
		t.Fatal("expected duplicate objectSpecifier")
	}
	if _, err := service.DecodeCreateObject([]byte{0x0e, 0x0f}, bacnet.DefaultDecodeLimits()); err == nil {
		t.Fatal("expected empty CHOICE")
	}
	if _, err := service.DecodeCreateObject([]byte{0x0e, 0x29, 0x01, 0x0f}, bacnet.DefaultDecodeLimits()); err == nil {
		t.Fatal("expected bad CHOICE tag")
	}
	if _, err := service.EncodeCreateObject(service.CreateObjectRequest{}); err == nil {
		t.Fatal("expected missing specifier encode error")
	}
}
