//go:build interop

// SPDX-License-Identifier: MIT

package interop

import (
	"context"
	"encoding/hex"
	"testing"
	"time"

	"github.com/otfabric/go-bacnet"
	"github.com/otfabric/go-bacnet/service"
)

// BACnetDestination for device:999, independently generated by BACnet4J 6.1.0
// Destination.write (Recipient device, processId=1, confirmed=true, all transitions).
// Recipient is context [0] ObjectIdentifier — accepted by bacnet-stack bacnet_recipient_decode.
var recipientListDestination = mustDecodeHex("8201feb400000000b4173b3b630c020003e72101118205e0")

func mustDecodeHex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

func listElementPeers() []struct {
	name  string
	image string
} {
	return []struct {
		name  string
		image string
	}{
		{"bacnet4j", bacnet4jImage()},
		{"bacnet-stack", getEnv("BACNET_STACK_IMAGE", defaultStackImage)},
	}
}

func destinationElements(t *testing.T) []bacnet.Element {
	t.Helper()
	els, n, err := bacnet.ParseSequence(recipientListDestination, bacnet.DefaultDecodeLimits(), -1)
	if err != nil || n != len(recipientListDestination) {
		t.Fatalf("parse destination: n=%d err=%v", n, err)
	}
	return els
}

func runAddRemoveListElementRecipientList(t *testing.T, image, adapter string) {
	t.Helper()
	// v3 ships NC-1; bacnet-stack also exposes NC instance 1 after Notification_Class_Init.
	t.Setenv("BACNET_DEVICE_FIXTURE", deviceBaselineV3Path(t))
	peer := startPeer(t, image, adapter,
		"DEVICE_FIXTURE_FILE=/fixtures/device/device-baseline-v3.json",
		"FIXTURE=device-baseline-v3",
	)
	if peer.assertedByReexec {
		return
	}
	c := newClient(t)
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	nc := bacnet.ObjectIdentifier{Type: bacnet.ObjectTypeNotificationClass, Instance: 1}
	const propRecipientList bacnet.PropertyIdentifier = 102
	els := destinationElements(t)

	if err := c.AddListElement(ctx, peer.target, service.ListElementRequest{
		Object:   nc,
		Property: bacnet.PropertyReference{Identifier: propRecipientList},
		Elements: els,
	}); err != nil {
		t.Fatalf("AddListElement: %v", err)
	}
	if err := c.RemoveListElement(ctx, peer.target, service.ListElementRequest{
		Object:   nc,
		Property: bacnet.PropertyReference{Identifier: propRecipientList},
		Elements: els,
	}); err != nil {
		t.Fatalf("RemoveListElement: %v", err)
	}
}

func TestAddRemoveListElementRecipientList(t *testing.T) {
	for _, p := range listElementPeers() {
		t.Run(p.name, func(t *testing.T) {
			runAddRemoveListElementRecipientList(t, p.image, p.name)
		})
	}
}
