name: CI
run-name: "CI (${{ github.event_name }}) on ${{ github.ref_name }} by @${{ github.actor }}"

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    uses: otfabric/.github/.github/workflows/go-ci.yml@v2
    with:
      codecov-name: go-bacnet
      go-versions: '["1.23", "1.24", "1.25", "1.26"]'
    secrets: inherit
